# Generated by Django 6.0.3 on 2026-03-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestador',
            name='disponivel',
            field=models.BooleanField(default=True, help_text='Quando falso, o prestador não entra no matching de solicitações.', verbose_name='disponível para matching'),
        ),
    ]
