[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = test_*.py *_tests.py tests.py
addopts =
    --reuse-db
    -ra
    --cov=users
    --cov=services
    --cov=ratings
    --cov=config
    --cov-report=term-missing
    --cov-report=xml
    --cov-fail-under=60
