# Generated by Django 6.0.3 on 2026-03-30 19:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('users', '0002_prestador_disponivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='nota')),
                ('comentario', models.TextField(blank=True, verbose_name='comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_feitas', to='users.motorista', verbose_name='motorista')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_recebidas', to='users.prestador', verbose_name='prestador')),
                ('solicitacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='services.solicitacao', verbose_name='solicitação')),
            ],
            options={
                'verbose_name': 'avaliação',
                'verbose_name_plural': 'avaliações',
                'ordering': ['-created_at'],
            },
        ),
    ]
