# Generated by Django 6.0.3 on 2026-03-30 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_prestador_disponivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('tipo_veiculo', models.CharField(max_length=100, verbose_name='tipo de veículo')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('a_caminho', 'A caminho'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='aceito em')),
                ('a_caminho_at', models.DateTimeField(blank=True, null=True, verbose_name='a caminho em')),
                ('concluded_at', models.DateTimeField(blank=True, null=True, verbose_name='concluído em')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelado em')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='users.motorista', verbose_name='motorista')),
                ('prestador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_atendidas', to='users.prestador', verbose_name='prestador')),
            ],
            options={
                'verbose_name': 'solicitação',
                'verbose_name_plural': 'solicitações',
                'ordering': ['-created_at'],
            },
        ),
    ]
